version: '3'
services:
  websocket:
    build: rakshitg600/notakto-socket-server
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

  payments:
    build: rakshitg600/notakto-socket-server
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
